"""add_autonomy_correction_and_permission_policy

Revision ID: be8eac7fc050
Revises: 0005_experiments
Create Date: 2026-07-08 19:34:31.221688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be8eac7fc050'
down_revision: Union[str, None] = '0005_experiments'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_policies',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('always_allowed_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('always_escalate_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_policies_tenant_id'), 'permission_policies', ['tenant_id'], unique=True)
    op.create_table('corrections',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('ai_draft_message', sa.Text(), nullable=False),
    sa.Column('human_edited_message', sa.Text(), nullable=True),
    sa.Column('was_edited', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corrections_conversation', 'corrections', ['conversation_id'], unique=False)
    op.create_index('ix_corrections_tenant', 'corrections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_corrections_tenant_id'), 'corrections', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('autonomy_level', sa.String(length=30), server_default='mode_1_supervised', nullable=False))
    op.add_column('tenants', sa.Column('min_reviewed_conversations', sa.Integer(), server_default='50', nullable=False))
    op.add_column('tenants', sa.Column('max_correction_rate', sa.Float(), server_default='0.10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'max_correction_rate')
    op.drop_column('tenants', 'min_reviewed_conversations')
    op.drop_column('tenants', 'autonomy_level')
    op.drop_index(op.f('ix_corrections_tenant_id'), table_name='corrections')
    op.drop_index('ix_corrections_tenant', table_name='corrections')
    op.drop_index('ix_corrections_conversation', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_permission_policies_tenant_id'), table_name='permission_policies')
    op.drop_table('permission_policies')
    # ### end Alembic commands ###
